name: Concurrency 2
run-name: Concurrency 2 (${{ inputs.environments }})
on:
    workflow_dispatch:
        inputs:
            environments:
                description: "Environment"
                type: environment
                required: true

concurrency: 
    group: ${{ github.workflow }} ${{ inputs.environments }}
    cancel-in-progress: true
jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 30